language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- docker pull mumuki/mumuki-python-worker
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo-deploy/master/travis_deploy
  && chmod u+x travis_deploy
- ./travis_deploy python
deploy:
  provider: rubygems
  api_key:
    secure: AzM6xVXMrEyd0P7VJV9ZHsghoZ6X/ZhpTt9pXTcEPJS3jH++rnN6dlX46P7HDpPesjtK1v4ALRCwu9mQV8L5RXlp5eYUoUAyriPLaOwotbGQKwcdGoA7arnIBRlcS4I1PV/FN7TtLt1E/+LNxQhnFeQcpTfetbNb3HR4p21JDe0JG78wSz8KLTbSqtzfoJgq1ZH1Hy9FdtkzY35qI+jKTwZPKBLFSleUvwaarUjxi1GJDII5GqG2P5pa3qO3YwpceV0+hMMoEVPln+Byiers1kUHxp0Q1UsKARNtGWCvshUlyda2zSTFRpmK6AuJ4SuPHP6jASjglxapEBn2Udyi1NVYUHbWTVkByPweE366Wpa+BDvcKZXmPlRk6ynNl+61wtmHUU3fv4WNUInEHZCeOGPqUs9SGGulALc/FX2D4jm59SHliZGtchh1j22Wiq2vgCtrqwpD15TIGLd+1KI5Bti0n/Marsw/JiR7fuMbvjmvm4SCNBJ3V9PZBtrCtmpdShch3euTexGYsRN6O0mvhZipDav1LbLR/uYDBEg1Vv4+fhz+YXH8ZvBSpWjk3vjiSe5koyu785XYPZsujFIg2kNhrrHP+CwKP8zw0uTIDhPFD9n8rLpECCekgyHbyB18W7ceE6UUjAKIxywAYQ6cFrFsX2tCyyWFH7n/D2C7MOI=
  gem: mumuki-python-runner
  on:
    tags: true
    repo: mumuki/mumuki-python-runner
